<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Hate_Crime [
<!ELEMENT Hate_Crime (crimes)>
<!ELEMENT Id (INCIDENT_ID, DATA_YEAR, ORI, PUB_AGENCY_NAME, PUB_AGENCY_UNIT, AGENCY_TYPE_NAME, STATE_ABBR, STATE_NAME, DIVISION_NAME, REGION_NAME)>

<!ELEMENT INCIDENT_ID (#PCDATA)>
<!ELEMENT DATA_YEAR (#PCDATA)>
<!ELEMENT ORI (#PCDATA)>
<!ELEMENT PUB_AGENCY_NAME (#PCDATA)>
<!ELEMENT PUB_AGENCY_UNIT (#PCDATA)>
<!ELEMENT AGENCY_TYPE_NAME (#PCDATA)>
<!ELEMENT STATE_ABBR (#PCDATA)>
<!ELEMENT STATE_NAME (#PCDATA)>
<!ELEMENT DIVISION_NAME (#PCDATA)>
<!ELEMENT REGION_NAME (#PCDATA)>

<!ATTLIST Hate_Crime row CDATA #REQUIRED>

]>


<Hate_Crime>
	<Crime id = "row 1">
		<INCIDENT_ID>3015</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0040200</ORI>
		<PUB_AGENCY_NAME>Rogers</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>
		
		<Crime id = "row 2">
		<INCIDENT_ID>3016</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0290100</ORI>
		<PUB_AGENCY_NAME>Hope</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>
		
		<Crime id = "row 3">
		<INCIDENT_ID>43</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0350100</ORI>
		<PUB_AGENCY_NAME>Pine Bluff</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>
		
		<Crime id = "row 4">
		<INCIDENT_ID>44</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0350100</ORI>
		<PUB_AGENCY_NAME>Pine Bluff</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>

		
		<Crime id = "row 5">
		<INCIDENT_ID>3017</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0350100</ORI>
		<PUB_AGENCY_NAME>Pine Bluff</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>

	<Crime id = "row 6">
		<INCIDENT_ID>3018</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0350100</ORI>
		<PUB_AGENCY_NAME>Pine Bluff</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>

	<Crime id = "row 7">
		<INCIDENT_ID>3019</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0600200</ORI>
		<PUB_AGENCY_NAME>Little Rock</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>


	<Crime id = "row 8">
		<INCIDENT_ID>45</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0600300</ORI>
		<PUB_AGENCY_NAME>North Little Rock</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>
		
		<Crime id = "row 9">
		<INCIDENT_ID>46</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0600300</ORI>
		<PUB_AGENCY_NAME>North Little Rock</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>
		
		
		<Crime id = "row 10">
		<INCIDENT_ID>3020</INCIDENT_ID>
		<DATA_YEAR>1991</DATA_YEAR>
		<ORI>AR0600300</ORI>
		<PUB_AGENCY_NAME>North Little Rock</PUB_AGENCY_NAME>
		<PUB_AGENCY_UNIT>none</PUB_AGENCY_UNIT>
		<AGENCY_TYPE_NAME>City</AGENCY_TYPE_NAME>
		<STATE_ABBR>AR</STATE_ABBR>	
		<STATE_NAME>Arkansas</STATE_NAME>
		<DIVISION_NAME>West South Central</DIVISION_NAME>
		<REGION_NAME>South</REGION_NAME>
	</Crime>
</Hate_Crime>

	
		